
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 05 14:02:06 MST 2020
//----------------------------------------------------

package sample;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 35;
  public static final int True = 39;
  public static final int Punto_y_coma = 25;
  public static final int Incremento = 37;
  public static final int Coma = 26;
  public static final int Bloque_abierto = 20;
  public static final int If = 5;
  public static final int Decremento = 38;
  public static final int Diferente = 33;
  public static final int Menor = 30;
  public static final int Else = 6;
  public static final int Equivale = 32;
  public static final int Error = 43;
  public static final int Mayor = 31;
  public static final int Str = 3;
  public static final int Clase_abierta = 23;
  public static final int Punto = 27;
  public static final int While = 13;
  public static final int Division = 19;
  public static final int Int = 4;
  public static final int For = 7;
  public static final int EOF = 0;
  public static final int Not = 36;
  public static final int And = 34;
  public static final int error = 1;
  public static final int Switch = 9;
  public static final int False = 40;
  public static final int Print = 12;
  public static final int Do = 8;
  public static final int Mayor_o_igual = 29;
  public static final int Case = 11;
  public static final int Bloque_cerrado = 22;
  public static final int Dos_puntos = 21;
  public static final int Identificador = 44;
  public static final int Resta = 17;
  public static final int Multiplicacion = 18;
  public static final int Numero = 42;
  public static final int Suma = 16;
  public static final int Dobl = 2;
  public static final int Clase_cerrada = 24;
  public static final int Main = 14;
  public static final int Igual = 15;
  public static final int Menor_o_igual = 28;
  public static final int Comillas = 41;
  public static final int Bol = 10;
}

