
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sample;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int True = 27;
  public static final int Punto_y_coma = 19;
  public static final int Incremento = 25;
  public static final int Coma = 20;
  public static final int Llave_b = 34;
  public static final int Llave_a = 33;
  public static final int If = 2;
  public static final int Void = 12;
  public static final int Decremento = 26;
  public static final int Else = 3;
  public static final int Error = 30;
  public static final int Corchete_b = 18;
  public static final int Corchete_a = 17;
  public static final int Str = 37;
  public static final int Punto = 21;
  public static final int While = 10;
  public static final int Division = 43;
  public static final int Int = 39;
  public static final int UMENOS = 44;
  public static final int Cadena = 36;
  public static final int Parentesis_b = 16;
  public static final int Parentesis_a = 14;
  public static final int For = 4;
  public static final int EOF = 0;
  public static final int DECIMAL = 32;
  public static final int Not = 24;
  public static final int error = 1;
  public static final int Switch = 6;
  public static final int False = 28;
  public static final int Operador_relacional = 22;
  public static final int Print = 9;
  public static final int Do = 5;
  public static final int Case = 8;
  public static final int Dos_puntos = 15;
  public static final int Identificador = 35;
  public static final int Operador_logico = 23;
  public static final int Resta = 41;
  public static final int Multiplicacion = 42;
  public static final int Numero = 31;
  public static final int Suma = 40;
  public static final int Dobl = 38;
  public static final int Main = 11;
  public static final int Igual = 13;
  public static final int Bol = 7;
  public static final int Comillas = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "If",
  "Else",
  "For",
  "Do",
  "Switch",
  "Bol",
  "Case",
  "Print",
  "While",
  "Main",
  "Void",
  "Igual",
  "Parentesis_a",
  "Dos_puntos",
  "Parentesis_b",
  "Corchete_a",
  "Corchete_b",
  "Punto_y_coma",
  "Coma",
  "Punto",
  "Operador_relacional",
  "Operador_logico",
  "Not",
  "Incremento",
  "Decremento",
  "True",
  "False",
  "Comillas",
  "Error",
  "Numero",
  "DECIMAL",
  "Llave_a",
  "Llave_b",
  "Identificador",
  "Cadena",
  "Str",
  "Dobl",
  "Int",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "UMENOS"
  };
}

